lab7/images/urls.py
from django.urls import path
from .views import image_list, detail, new, new_comment

app_name = "images"
urlpatterns = [
    path('', image_list, name="list"),
    # /images/5/ -> images:detail
    path('<int:image_id>/', detail, name="detail"),
    # /images/new/ -> images:new
    path('new/', new, name="new"),
     # /images/new/ -> images:new
    path('<int:image_id>/comments/new/', new_comment, name="new_comment"),

]

lab7/myimgur/urls.py
from django.contrib import admin
from django.urls import path, include
from images.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', home, name="home"),
    path('slike/', include('images.urls')),
]

lab7/images/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    title = models.CharField(max_length=128)
    url = models.CharField(max_length=512)
    pub_date = models.DateTimeField()

    def __str__(self):
        return f"{self.id}: {self.title}"
    
class Comment(models.Model):
    image= models.ForeignKey(Image, on_delete=models.CASCADE)
    text=models.CharField(max_length=512)
    name=models.CharField(max_length=128)
    created_at=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.id}: {self.image.title} -> {self.text}"

lab7/images/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Image
from django.urls import reverse

# Create your views here.
def home(request):
    context = {}
    return render(request, 'images/home.html', context)

def image_list(request):
    sort=request.GET.get('sort', 'asc')
    if sort=="desc":
        images=Image.objects.order_by("-pub_date")
    else:
        images=Image.objects.order_by("pub_date")

    context = {
        'images': images,
    }
    return render(request, 'images/list.html', context)

def detail(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    #comments= Comment.object,filter(image=image)
    comments= image.comment_set.all()
    context = {
        'image': image,
                'comments' : comments,

    }
    return render(request, 'images/detail.html', context)

def new(request):
    if request.method=="POST":
        title=request.POST['title']
        url=request.POST['URL']
        pub_date=request.POST['pub_date']
        
        image= Image(title=title,url=url,pub_date=pub_date,)
        image.save()
        return HttpResponseRedirect(
            reverse('images:detail', args=(image.id,))
        )
    context= {}
    return render(request, 'images/new.html', context)

def new_comment(request, image_id):
    image= get_object_or_404(Image, pk=image_id)
    if request.method == "POST":
        text=request.POST['text']
        name=request.POST['name']
        image.comment_set.create(
            text=text,
            name=name,
        )
    return HttpResponseRedirect(
        reverse('images:detail', args=(image_id,))
    )

lab7/images/templates/images/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyImgur</title>
</head>
<body>
    <div>
        <a href="/">MyImgur</a>
        <a href="{% url 'images:list' %}">All images</a>
        <a href="{% url 'images:new' %}">Submit new image</a>
    </div>
    <div>   
        {% if request.user.is_authenticated%}
            Prijavljen: {{request.user.username}}
            <a href='{% url 'logout' %}'>Odjava</a>
        {% else %}
            <a href={% url 'login' %}>Prijava</a>
         {% endif %}   
    </div>
    <div>
        {% if request.user.is_superuser %}
        <a href= "/admin">Admin</a>
        {% endif %}   

    </div>

    <h1>Welcome to MyImgur</h1>
    {% block content %}
    {% endblock content %}

</body>
</html>

lab7/images/templates/images/detail.html
{% extends 'images/base.html' %}

{% block content %}
<h1>{{ image.title }}</h1>
<p>{{ image.pub_date }}</p>
<img src="{{ image.url }}" style="width: 600px;">

<h1>Komentari</h1>
<div>
    <form action="{% url 'images:new_comment' image.id %}" method="post">
        <label for="">Name</label>
        <input type="text" name="name" id=""> <br>
        <label for="">Text</label>
        <input type="text" name="text" id=""> <br>
        <input type="submit" value="Komentiraj">
        {% csrf_token %}

    </form>
</div>
{% for comment in comments %}
<p> 
    <strong>{{comment.name}}:</strong>
    {{comment.text}} <br>
    <small>{{comment.created_at}}</small>
</p>
{% empty %}
<p> Nitko nije komentrao, budi prvi!!!! </p>

{%endfor%}

{% endblock content %}

lab7/images/templates/images/home.html
{% extends 'images/base.html' %}

{% block content %}
    <a href="{% url 'images:list' %}">Vidi naše slike!</a>
{% endblock content %}

lab7/images/templates/images/list.html
{% extends 'images/base.html' %}

{% block content %}
<div>
    <form action="#" method="get">
        <select name="sort" onchange="this.form.submit()">
                <option selected disabled>Chose sort</option>
                <option value="asc">Ascending</option>
                <option value="desc">Discending</option>
        </select>
    </form>
</div>
    {% for image in images %}
        <h3>
            <a href="{% url 'images:detail' image.id %}">{{ image.title }}</a>
        </h3>
        <p><small>{{ image.pub_date }}</small></p>
        <img src="{{ image.url }}" style="width: 150px;">
    {% endfor %} 

{% endblock content %}

lab7/images/templates/images/new.html
 {% extends 'images/base.html' %}

{% block content %}

<h1> Submit new image </h1>

<form action="" method="post">
    {% csrf_token %}
    <label for ="">Title</label>
    <input type="text" name="title" id=""> <br>
    <label for="">URL</label>
    <input type="text" name="URL">          <br>
    <label for="">Published at</label>
    <input type="date" name="pub_date">       <br>
    <input type="submit" value="Submit image">
</form>





{% endblock content %}